/*

 SPRITESET_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 23

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __spriteset_tiles_h_INCLUDE
#define __spriteset_tiles_h_INCLUDE

/* Bank of tiles. */
#define spriteset_tilesBank 0
/* Start of tile array. */
extern const unsigned char spriteset_tiles[];

#endif

/* End of SPRITESET_TILES.H */
