/*

 TILESET_GRID.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tileset_grid_h_INCLUDE
#define __tileset_grid_h_INCLUDE

/* Bank of tiles. */
#define tileset_gridBank 0
/* Start of tile array. */
extern const unsigned char tileset_grid[];

#endif

/* End of TILESET_GRID.H */
