/*

 TILEMAP_GRID.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\schuyler\projects\gameboy_dev\gb2048\img\gb2048_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 96
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tilemap_grid_h_INCLUDE
#define __tilemap_grid_h_INCLUDE

#define tilemap_gridWidth 20
#define tilemap_gridHeight 18
#define tilemap_gridBank 0

extern const unsigned char tilemap_grid[];

#endif

/* End of TILEMAP_GRID.H */
